### ISSUE TITLE
Failed to call into JavaScript module method RCTEventEmitter.receiveEvent()

### ISSUE THREAD

**Issue by okwasniewski** [callstack/react-native-visionos#164]
### Description

When using `react-native-bottom-tabs` with 0.77 RC this issue pops up: 

```
console.js:614 Error: Failed to call into JavaScript module method RCTEventEmitter.receiveEvent(). Module has not been registered as callable. Registered callable JavaScript modules (n = 9): AppRegistry, HMRClient, GlobalPerformanceLogger, RCTNativeAppEventEmitter, SamplingProfiler, RCTDeviceEventEmitter, RCTLog, HeapCapture, Systrace. Did you forget to call `registerCallableModule`?
```

The app works on 0.76, looks like this is an issue with visionOS RC

### Steps to reproduce

-

### React Native Version

0.77.0-RC

### Affected Platforms

Other (please specify)

### Output of `npx react-native info`

```text
a
```

### Stacktrace or Logs

```text
a
```

### Reproducer

a

**Comment by okwasniewski** [comment]
Turns out version 0.77 was missing the newly introduced RCTAppDependencyProvider from the template; 

```swift
  override func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
    self.dependencyProvider = RCTAppDependencyProvider()
    
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
```

After adding it, everything works again.
